### ISSUE TITLE
Building docs with local copy

### ISSUE THREAD

**Issue by javierggt** [sot/cxotime#18]
I don't know why I did not see this before merging the docs branch.

With the current master branch (after merging #12). When I do `make html` in the `docs` directory, I get this:
```
WARNING: autodoc: failed to import module 'cxotime' from module 'cxotime'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/javierg/SAO/miniconda3-shiny/envs/ska3-shiny/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 32, in import_module
    return importlib.import_module(modname)
  File "/Users/javierg/SAO/miniconda3-shiny/envs/ska3-shiny/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/javierg/SAO/git/cxotime/cxotime/__init__.py", line 2, in <module>
    from .cxotime import CxoTime  # noqa
  File "/Users/javierg/SAO/git/cxotime/cxotime/cxotime.py", line 24, in <module>
    libpt = npct.load_library("parse_times", Path(__file__).parent)
  File "/Users/javierg/SAO/miniconda3-shiny/envs/ska3-shiny/lib/python3.8/site-packages/numpy/ctypeslib.py", line 157, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension
```

So it seems it tries to load a library in a hardwired relative location.

If I comment [conf.py:23](https://github.com/sot/cxotime/blob/master/docs/conf.py#L23), then it "works" but of course it uses the installed version.

Any idea?

I could swear that I built the local copy before...

**Comment by taldcroft** [comment]
I did a `python setup.py build_ext --inplace` first and it made the docs ok apart from expected warnings about section headers.

**Comment by taldcroft** [comment]
@javierggt - does my suggestion work for you to close this issue?

**Comment by javierggt** [comment]
This fixes this issue.
