### ISSUE TITLE
Missing parse_times library

### ISSUE THREAD

**Issue by javierggt** [sot/cxotime#19]
Another issue with the same error.

I created a new environment on kady. These were the commands:
```
conda create -n cxotime
conda activate cxotime
conda install -c https://ska:$CONDA_PASSWORD@cxc.cfa.harvard.edu/mta/ASPECT/ska3-conda/masters -c https://icxc.cfa.harvard.edu/aspect/ska3-conda/shiny cxotime
python -m cxotime
```

and this is the error:
```
Traceback (most recent call last):
  File "/export/jgonzale/github-workflows/miniconda3-shiny/envs/cxotime/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/export/jgonzale/github-workflows/miniconda3-shiny/envs/cxotime/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/export/jgonzale/github-workflows/miniconda3-shiny/envs/cxotime/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/export/jgonzale/github-workflows/miniconda3-shiny/envs/cxotime/lib/python3.8/site-packages/cxotime/__init__.py", line 2, in <module>
    from .cxotime import CxoTime  # noqa
  File "/export/jgonzale/github-workflows/miniconda3-shiny/envs/cxotime/lib/python3.8/site-packages/cxotime/cxotime.py", line 24, in <module>
    libpt = npct.load_library("parse_times", Path(__file__).parent)
  File "/export/jgonzale/github-workflows/miniconda3-shiny/envs/cxotime/lib/python3.8/site-packages/numpy/ctypeslib.py", line 157, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension
```

In my mac I have a file called `parse_times.cpython-38-darwin.so` along with cxotime.py. I do not see such file in the kady install. Any idea where to look?

**Comment by javierggt** [comment]
My guess right now is that the library was not build when the conda package was built. I am checking why now.

**Comment by javierggt** [comment]
It seems that numpy is required to build: https://github.com/sot/cxotime/blob/master/setup.py#L20

Numpy is not listed in the build requirements in meta.yml. If the try statement in setup.py fails, setup ignores it and the extension is just not built. Could that be it?
